services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: src/Dockerfile
  #   container_name: api
  #   restart: always
  #   ports:
  #     - "8088:80"
  #     - "8082:443"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Host=db;Database=myapidb;Username=myuser;Password=mypassword
  #   depends_on:
  #     - db
      
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./.docker/data/postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"

volumes:
  db:
    driver: local